alias reload!='. ~/.zshrc'
alias rspec='nocorrect rspec'
alias cap='nocorrect cap'
alias gvim='mvim -p'
alias ll='ls -alF'
alias jest='nocorrect jest'
alias letswork='tilix --session ~/pff.json --session ~/ultimate.json --session ~/galaxy.json; exit'
